sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "12"

before_script:
  - npm install -g @angular/cli@9.1.15

script:
  - npm install
  - ng build --prod --aot
  - ng test
  - ng lint
