sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "11"

before_script:
  - npm install -g @angular/cli@6.2.3

script:
  - npm install
  - ng build --prod --aot
  - ng test
  - ng lint
