name: Build and Test CI

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Build
        run: |
          npm install -g @angular/cli@8.3.20
          npm install
      - name: Test
        run: |
          ng build
          ng test
          ng lint
